name: flutter_test_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-11.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: SFProText
    fonts:
      - asset: fonts\sfpt\SFProText-Regular.ttf
        weight: 100
      - asset: fonts\sfpt\SFProText-Medium.ttf
        weight: 200
      - asset: fonts\sfpt\SFProText-Bold.ttf
        weight: 600
      - asset: fonts\sfpt\SFProText-Heavy.ttf
        weight: 700
  assets:
    - assets/

